### ISSUE TITLE
Update React and Dependencies

### ISSUE THREAD

**Issue by NicolaOsborne** [edina/CuriousEdinburgh2#89]
George has noted that we now need to update React and the various dependencies. Please do this as the first stage of the snagging work and log any new issues that may arise from this.

**Comment by gmh04** [comment]
I've spent the morning upgrading the app dependencies.  Most importantly, RN 0.42 to 0.48.  There were a number of android build issues that have been resolved, and would be surprised if @jollopre got IOS building problem free, so instead of doing a pull request to master you can try this branch first:

https://github.com/edina/CuriousEdinburgh2/tree/issue-89-upgrade-deps

There were 100s of jslint warning and errors, that I decided due to time constrains to revert back to old version, that can be done when/if we get more time.  A couple of tests are also broken that I could not easily fix by downgrading and since I'm out of time will leave at the moment (otherwise I will have no time to add new feature(s) - the whole point of the release).  But the in andoid is working fine.

**Comment by jollopre** [comment]
For iOS:

- Fixed corrupted file at ios/CuriousEdinburgh.xcodeproj/project.pbxproj
- Remove tag keyCommands at ios/CuriousEdinburgh/LaunchScreen.storyboard

For both:
- Added prop-types for checking components prop types at development since react 16 will be dropping this code in favour of the added library.
