### ISSUE TITLE
Enable social media sharing from the app

### ISSUE THREAD

**Issue by NicolaOsborne** [edina/CuriousEdinburgh2#90]
From the tour stop pages: enable social media sharing of the page. 

**Channels** 
- Facebook
- Twitter
- Email
- Instagram (if available)

**What should be shared?**
- Title of page
- URL of (blog) page
- First thumbnail from tour stop
- @curiousedi handle.

Suggested format:
"Exploring <Page Title> with @curiousedi. <URL> <Image URL>"

**Comment by gmh04** [comment]
Due to a runtime error with RN 0.48 (undefined is not an object (evaluating '_react2.default.PropTypes.func') in DefaultTabBar.js in react-native-scrollable-tab-view) I have had to downgrade to RN 0.47.  This is a shame as a Sharing dialog is now available in the core api https://facebook.github.io/react-native/docs/share.html which is not in 0.47.  So I have installed https://github.com/EstebanFuentealba/react-native-share which works and looks mature.  In android clicking on the share link invokes the native sharing popup,

I just need from @NicolaOsborne an idea of how you want this to look on this page.  It is currently a simple link below Associated Links.

**Comment by NicolaOsborne** [comment]
@gmh04 can you provide a screenshot of this or demo it so I have an idea of what is possible please?

**Comment by gmh04** [comment]
I've just added a link to the bottom of the page, to get an idea of what the share will look like on different devices see https://facebook.github.io/react-native/docs/share.html 
![screenshot_20170912-110119](https://user-images.githubusercontent.com/611548/30320498-bac2bf10-97aa-11e7-98ca-72f08e15f09a.png)

**Comment by gmh04** [comment]
also @NicolaOsborne, look at the options for sharing.  The url is either a url (of the tour stop or a base64 image) see https://github.com/EstebanFuentealba/react-native-share#user-content-openoptions.  Presumably you would prefer the URL of the tour stop and drop the first thumbnail from tour stop?  You want the message to be ""Exploring with @curiousedi. "?

**Comment by NicolaOsborne** [comment]
Thanks @gmh04. 

For the tourstop page: rather than "Simple Share" can we please change the text to "Share this Tour Stop"? 

For the sharing options:

- URL should be the tour stop
- Exploring <Tour Stop Name/Title of Page> with @curiousedi

If the tour stop name is not doable, then yes, "Exploring with @curiousedi" would be fine.

**Comment by gmh04** [comment]
Android done. assigning to @jollopre for IOS setup: https://github.com/EstebanFuentealba/react-native-share#user-content-ios
