### ISSUE TITLE
Change preview image for social media sharing - Android & iOS app

### ISSUE THREAD

**Issue by NicolaOsborne** [edina/CuriousEdinburgh2#98]
We've had a request through:

"The social media links work, but no picture is appearing in twitter and the picture that comes up in Facebook is of the curious Edinburgh logo. Ideally we would like to have the picture of the location (so first picture of the line-up) but if it is the logo we would like the whole logo (now its only partially visible so the name is not readable)."

Please can you:
- Confirm whether you can change the preview image appearing in Twitter
- If this is changeable, please re-set to first image in a post. 

- Confirm whether you can change the preview image appearing in Facebook
- If this is changeable, please re-set to first image in a post. 
- If the first image in the post is not possible, please ensure that logo is sharing at a suitable aspect ratio to appear in full in Facebook posts (myself or Jackie can assist if needed).

**Comment by gmh04** [comment]
@NicolaOsborne In android, only a title and message is supported, see https://facebook.github.io/react-native/docs/0.49/share.html.  It maybe possible to add a base64 image to the URL field for IOS.  If one platform solution acceptable, then maybe @jollopre could investigate?

**Comment by NicolaOsborne** [comment]
Thanks @gmh04. Let me know what's possible in iOS @jollopre and we can decide from there.

**Comment by gmh04** [comment]
@NicolaOsborne It turns out URL works for android too ... kind of.  It works well for twitter (showing message and image), but not so well for Facebook.  The images below are a before and after, you will see that the message is missing.  Will be good to see what it looks like on IOS.

![screenshot_20171208-142948](https://user-images.githubusercontent.com/611548/33772644-43a7d8c6-dc2d-11e7-80a4-f26e342ba53e.png)
![screenshot_20171208-143141](https://user-images.githubusercontent.com/611548/33772659-511394f0-dc2d-11e7-8159-ddf6adf16138.png)

**Comment by NicolaOsborne** [comment]
I think that looks acceptable - the image for the tour stop will scale way down for the preview image that will be seen when shared.
